name: Build Android APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: '9.6.1'

      - name: Build APK
        # 安卓打包命令 (现在会自动使用 debugmt.keystore 签名)
        run: gradle :app:assembleRelease

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: brarchive-app
          # 【修改点】：提取已签名的 release apk，去掉 -unsigned
          path: app/build/outputs/apk/release/app-release.apk
